version: '3'
services:
  db:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fmanagement

  app:
    build: ./
    image: friendmanagement
    depends_on:
      - db
    links:
      - db
    ports:
      - "8080:8080"